---
x-common-env: &cenv
    MYSQL_ROOT_PASSWORD: hjgg786HGJv7932
    GIT_REPOSITORY: https://github.com/mhus/coolweb-test-sample.git
    GIT_BRANCH:
    GIT_USER:
    GIT_TOKEN:
    GIT_PRIVATE_KEY:

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./volumes/db/data:/var/lib/mysql
        environment:
            <<: *cenv
        networks:
        - internal
    init:
        build:
            context: ./init
        environment:
            <<: *cenv
        volumes:
            - ./volumes/html:/mnt/html
            - ./volumes/nginx_config:/mnt/nginx_config
            - ./volumes/php_config:/mnt/php_config
        depends_on:
            db:
                condition: service_started
        networks:
        - internal
    nginx:
        image: nginx
        volumes:
            - ./volumes/nginx_config:/etc/nginx/conf.d
            - ./volumes/html:/var/www/html
        ports:
            - 9999:80
        depends_on:
            init:
                condition: service_completed_successfully
        networks:
        - internal
    php:
        build:
            context: ./php
        volumes:
        - ./volumes/html:/var/www/html/
        - ./volumes/php_config:/usr/local/etc/php/conf.d
        - ./volumes/logs/php.log:/var/log/fpm-php.www.log
        depends_on:
            init:
                condition: service_completed_successfully
        networks:
        - internal
networks:
  internal:
    driver: bridge
